# Generated by Django 4.2.1 on 2023-09-17 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuzolouser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='fuzolouser',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
