# Generated by Django 4.2.1 on 2023-09-18 07:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_fuzolouser_is_staff_alter_fuzolouser_is_superuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuzolouser',
            name='pickup_manager',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='fuzolouser',
            name='is_verified',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='FuzoloUserDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('points', models.IntegerField(default=0)),
                ('email_verified', models.BooleanField(default=False)),
                ('footbal_membership_id', models.CharField(default='--', max_length=255)),
                ('cricket_membership_id', models.CharField(default='--', max_length=255)),
                ('phone_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
