# Generated by Django 4.2.6 on 2023-10-30 05:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_fuzolouser_pickup_manager_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAddPoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('points', models.IntegerField(default=0)),
                ('razorpay_id', models.CharField(max_length=255)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('phone_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
