# Generated by Django 4.2.6 on 2023-10-30 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_useraddpoints_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddpoints',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='useraddpoints',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
