# Generated by Django 4.2.1 on 2023-09-19 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pickup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('game_id', models.CharField(max_length=50)),
                ('day', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('duration', models.IntegerField()),
                ('start_time', models.CharField(max_length=20)),
                ('end_time', models.CharField(max_length=20)),
                ('reporting_time', models.CharField(max_length=20)),
                ('max_players', models.IntegerField()),
                ('price_per_player', models.IntegerField()),
                ('hourly_price', models.IntegerField()),
                ('joined_players', models.IntegerField()),
                ('waiting_list', models.CharField(max_length=200)),
                ('wallet_list', models.CharField(max_length=200)),
                ('venue', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PickupPlayers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('remark', models.CharField(default='No Show', max_length=20)),
                ('present', models.BooleanField(default=False)),
                ('present_timestamp', models.DateTimeField(auto_now=True)),
                ('manager_added', models.BooleanField(default=True)),
            ],
        ),
    ]
