# Generated by Django 4.2.6 on 2023-10-27 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuzolo_pickup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickup',
            name='confimed',
            field=models.BooleanField(default=False),
        ),
    ]
