# Generated by Django 4.2.6 on 2023-10-27 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fuzolo_pickup', '0002_pickup_confimed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pickup',
            old_name='confimed',
            new_name='confirmed',
        ),
    ]
